### ISSUE TITLE
Error: command hello:world not found

### ISSUE THREAD

**Issue by hectorvp** [oclif/hello-world#36]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
This is a bug.

What is the current behavior?
-----------------------------

Command `./bin/run hello:world `not working.

Steps to reproduce -
-----------------------
Commands fired  - 
```
$ oclif generate stream
$ ./bin/run hello:world
Error: command hello:world not found
```

generate command pulls oclif/hello-world repo as a template.

What is the expected behavior?
------------------------------
hello world! (./src/commands/hello/world.ts)

**versions**-
**oclif:** 2.1.0
**oclif/core:** 1.1.0
**OS:** OSX 11.5.2
**Node:** 14.17.1

**Comment by peternhale** [comment]
@hectorvp thank you for reporting this issue.

Did you run build on the resulting project? Either `yarn build` or `npm run build`?

**Comment by hectorvp** [comment]
Thanks @peternhale. How silly of me! `npm run build` worked.
